version: '3.9'

services:
  hz:
    image: hazelcast/hazelcast:5.1
    environment:
      - JAVA_OPTS=-Dhazelcast.config=/opt/hazelcast/config-ext/hazelcast.yaml
    volumes:
      - $PWD/config-ext/:/opt/hazelcast/config-ext/:ro

  hz_001:
    extends: hz

  hz_002:
    extends: hz
  
  hz_003:
    extends: hz
  
  hz_mc:
    image: hazelcast/management-center:5.1
    depends_on:
      - hz_001
      - hz_002
      - hz_003
    ports:
      - 8080:8080
    environment:
      - MC_INIT_CMD=/opt/hazelcast/management-center/bin/mc-conf.sh cluster add -H=/data -ma hz_001:5701,hz_002:5701,hz_003:5701 -cn dev
  
  app:
    build: app
    volumes:
      - $PWD/app/main.py:/usr/src/app/main.py:ro
    
  clear_map:
    extends: app
    depends_on:
      - hz_mc
    command: "MAP_CLEAR"
  
  fill_map:
    extends: app
    depends_on:
      - hz_mc
    command: "MAP_PUT"

  map_without_locking: 
    extends: app
    depends_on:
      - hz_mc
    command: "MAP_LCK_NO"

  map_pessimistic_locking: 
    extends: app
    depends_on:
      - hz_mc
    command: "MAP_LCK_PSM"
  
  map_optimistic_locking:
    extends: app
    depends_on:
      - hz_mc
    command: "MAP_LCK_OPM"

  clear_queue:
    extends: app
    depends_on:
      - hz_mc
    command: "Q_CLEAR"

  queue_producer:
    extends: app
    depends_on:
      - hz_mc
    command: "Q_PRD"

  queue_consumer:
    extends: app
    depends_on:
      - hz_mc
    command: "Q_CNM"