FROM python:3.10-slim

COPY ./requirements.facade.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./facade/ ./app/facade/
COPY ./common/ ./app/common/
COPY ./api/ ./app/api/

ENTRYPOINT [ "uvicorn", "app.facade:app", "--host", "0.0.0.0", "--port", "8080" ]