FROM python:3.10-slim

COPY ./requirements.messages.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./messages/ ./app/messages/
COPY ./common/ ./app/common/
COPY ./api/ ./app/api/

ENTRYPOINT [ "uvicorn", "app.messages:app", "--host", "0.0.0.0", "--port", "8080" ]